### ISSUE TITLE
passing arguments to commands

### ISSUE THREAD

**Issue by timoxley** [jedi4ever/ttyrec.js#3]
What's up with this: https://github.com/jedi4ever/ttyrec.js/blob/52e039f1e1d91df4dcff6cc7a78f262be2c71740/bin/ttyrec#L37

**Comment by jedi4ever** [comment]
ha! pty.spawn takes the arguments as a separate part.

We should shell-parse the '-e' shellcommand passed and pass it as separate args to the pty.spawn command.
Just haven't gotten around to it.

The alternative approach is to provide another argument to the ttyrec.js , but I wanted to mimic the original ttyrec cli args.

**Comment by jedi4ever** [comment]
But since you asked - here is the fix - https://github.com/jedi4ever/ttyrec.js/commit/0b53640236ddb41e5863bd37f3e67a259705ea6a

**Comment by jedi4ever** [comment]
@timoxley closing this issue as I think the commit resolved it. Feel free to re-open if needed.

**Comment by timoxley** [comment]
@jedi4ever thanks for the quick response! I didn't get a chance to play with it yet, will let you know how I go. :+1:
