### ISSUE TITLE
client side player?

### ISSUE THREAD

**Issue by soichih** [jedi4ever/ttyrec.js#4]
Is there anyway you could make ttyplay to work on the browser? I can then use some ttyrecording on my reveal.js presentations or such..

**Comment by jedi4ever** [comment]
I currently have dist/ttyrec.js (created by browersify)

My tests work browserside for both rec/play stream (see test/index.html). But it needs some  love if you want to write uft8 chars without converting them to a Buffer. +  it still needs to be minified for production use.

To make it a full client-side player, I first want to create something that understands the tty escape codes. Work is underway in another project of mine http://github.com/jedi4ever/terminal-parser . This is intended a re-usable parser.

_Note:_ I'm aware of tty.js and headless-terminal , but I want to create a generic parser/token stream for it and base other browser buffers, browser terminals (dom based, canvas based) ..., console terminals on it. 

In all projects I've seen the encoding/decoding of the tty is tightly coupled with the rendering side. (like you probably noticed with tty.js) .

**Comment by jedi4ever** [comment]
@soichih you might also want to take a look at - http://www.fact-project.org/termtv/ as an alternative to jsttyplayer
